#Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: Metrics

on:
  # Everyday at 6pm
  schedule: [{cron: "0 18 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: anthonyjdella
          template: classic
          base: header
          config_timezone: America/Chicago
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
  github-metrics-2:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: anthonyjdella
          template: terminal
          base: activity, community
          config_timezone: America/Chicago
          plugin_gists: yes
