#Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference

name: Metrics

on:
  # Everyday at 6pm
  schedule: 
    - cron: "0 18 * * *"
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: anthonyjdella
          template: classic
          base: header
          config_timezone: America/Chicago
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.two.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: anthonyjdella
          template: terminal
          base: activity, repositories
          config_timezone: America/Chicago
